strings = ["CNBICIRCLEHRABTSQUAREUBYSPT",

"ABAPPLEKRSDHDAETGEWPDTBVNMD",

"TRNSBMMNIVTACANDLEPIQSNERLT",

"EHUICDUDXDHPXIVPSSJESFHOMEV",

"GEVWEGNIWTCOURAGEOHEPDUAESE",

"OOFIRETTPNMEFNASICTWRMEVLET",

"RMGVXIOCBINMDUAEMILMBOLDHDR",

"INFOPAFJEPNCLUBASBEOMCWNIUS",

"ZLUNGAEHEBNREIVPRVOEHFNTIOR",

"EAEMUSICSOSWRZTSGEGITGTVRR",

"ONOSPIRITVSCSIASVRDEWCVNIMY",

"VTKNVOTWLAFMEEMEEGRAPENECSO",

"EEPAHSSWINDIWATERTYTSTNURRE",

"REJKELMLSZBSMRYKQIEARTHDAEL" ,

"LEUFZTSDSWCHSHXKIDNEYTAEGAE",

"ARAINOXLASDHEPWTALDUAJECDTB",

"PSDSGHILIOSRZASWEAGSPADEVPA",

"SSHWIHORANGEFSFNIOKBANANAWN",

"OHWNTDIAMONDUFEAUFSDBFRHDSF",

"RGLEOXOTHUTTUFBUWENMSUNCEPE",

"TALSWGRNMOBRAINRSEUVDSSSVSE",
]
for string in strings:
    #for j in range(3, 10):
    output = [string[i:(i+5)] for i in range(len(string)-2) if 'h' in string[i:(i+5)]]
    print('5_letters: ', output)
